### PR TITLE
Add NRPE check for OpenStack loadbalancer

### PR DESCRIPTION
**Pull request by r-f-g**
This review will provide NRPE checks on OpenStack loadbalancers that are managed by the openstack-integrator. 
These checks on behalf of Kubernetes will ensure that all OpenStack loadbalancers configured by the openstack-integrator are monitored and reported via the nagios system.

Adding all the checks NRPE requires extensive changes and therefore it's divided into two parts. This is the second part of the changes and includes NRPE check for loadbalancers. 
This is an nasty branch and branch #43  is required to be merged before merging.

Related-Bug: [#1853886][bug1853886]

How I tested it:
 1. I went according to the tutorial [1]
 1. I deployed octavia with bundle.yaml [2] and configure it with these steps [3]
 1. I deployed kubernetes-code, kube-api-load-balancer and openstack-integrator on the new Openstack [4] 
 1. After successful execution of the `hooks/nrpe-external-master-relation-changed`, I ssh to the `openstack-integrator` unit and ran commands [5]

---
[1]: https://discourse.charmhub.io/t/how-to-deploy-openstack-on-openstack-and-bootstrap-a-juju-env-on-top-of-it/4189
[2]: https://pastebin.ubuntu.com/p/MqdwjQS4nj/
[3]: https://docs.openstack.org/project-deploy-guide/charm-deployment-guide/latest/app-octavia.html#configuration
[4]: https://pastebin.ubuntu.com/p/8FY5NGDSys/
[5]: https://pastebin.ubuntu.com/p/qM5WyqPmWw/
[bug1853886]: https://bugs.launchpad.net/charm-openstack-integrator/+bug/1853886

### CODE REVIEW

**Review by auria — COMMENTED** [review]
Please find a few comments inline. I'm in the process of manually testing this PR (which effectively tests the whole bug fix). Thank you.

**Comment by auria** [comment]
When trying to manually test the fix, I found several issues.

The tutorial in [1] has been fixed after testing. However, after following all the steps, there is the requirement to deploy Octavia using the shared bundle in [2]. That bundle is an overlay, and if added to the deployment CLI call in the tutorial, `ovn-chassis`' `bridge-interface-mappings` is overwritten. I had to run `juju config ovn-chassis bridge-interface-mappings="$BRIDGE_INTERFACE_MAPPING"` again.

I then ran:

```
$ juju run-action octavia/0 --wait configure-resources
unit-octavia-0:
  UnitId: octavia/0
  id: "14"
  results:
    Stderr: |
      ovs-vsctl: no row "o-hm0" in table Interface
    Stdout: |
      none
      none
  status: completed
  timing:
    completed: 2021-02-26 11:17:05 +0000 UTC
    enqueued: 2021-02-26 11:16:19 +0000 UTC
    started: 2021-02-26 11:16:19 +0000 UTC
```

I was expecting the `o-hm0` interface to be created, and I'm not sure if an error should occur regarding `ovs-vsctl`, because OVN is into play.

Finally, I think there is a step missing to generate the amphorae image by converting a standard Ubuntu image.

Please let me know if there is any link (such as the [app-octavia](https://docs.openstack.org/project-deploy-guide/charm-deployment-guide/latest/app-octavia.html) appendix from the Charm Deployment Guide) with further info I should follow. But I would like to fix the `configure-resources` step, first. Maybe I'm only missing the certificates configuration in Octavia?

Thank you.

**Comment by r-f-g** [comment]
> When trying to manually test the fix, I found several issues.
> 
> The tutorial in [1] has been fixed after testing. However, after following all the steps, there is the requirement to deploy Octavia using the shared bundle in [2]. That bundle is an overlay, and if added to the deployment CLI call in the tutorial, `ovn-chassis`' `bridge-interface-mappings` is overwritten. I had to run `juju config ovn-chassis bridge-interface-mappings="$BRIDGE_INTERFACE_MAPPING"` again.
> 
> I then ran:
> 
> ```
> $ juju run-action octavia/0 --wait configure-resources
> unit-octavia-0:
>   UnitId: octavia/0
>   id: "14"
>   results:
>     Stderr: |
>       ovs-vsctl: no row "o-hm0" in table Interface
>     Stdout: |
>       none
>       none
>   status: completed
>   timing:
>     completed: 2021-02-26 11:17:05 +0000 UTC
>     enqueued: 2021-02-26 11:16:19 +0000 UTC
>     started: 2021-02-26 11:16:19 +0000 UTC
> ```
> 
> I was expecting the `o-hm0` interface to be created, and I'm not sure if an error should occur regarding `ovs-vsctl`, because OVN is into play.
> 
> Finally, I think there is a step missing to generate the amphorae image by converting a standard Ubuntu image.
> 
> Please let me know if there is any link (such as the [app-octavia](https://docs.openstack.org/project-deploy-guide/charm-deployment-guide/latest/app-octavia.html) appendix from the Charm Deployment Guide) with further info I should follow. But I would like to fix the `configure-resources` step, first. Maybe I'm only missing the certificates configuration in Octavia?
> 
> Thank you.

I'm not sure why `ovn-chassis' bridge-interface-mappings is overwritten and I don't remember if it happened to me.

My `o-hm0` is there and it's working. I'm not sure that this could be caused by missing certificates. I exported the whole package [1], maybe it will help you.

Yes, you are right that there is no step here and I added it to the description. [2]

---
[1]: https://pastebin.ubuntu.com/p/VDQYy8SZGt/
[2]: https://docs.openstack.org/project-deploy-guide/charm-deployment-guide/latest/app-octavia.html#configuration

**Comment by r-f-g** [comment]
This PR has been replaced with #64.

**Pull request closed without merging**
